Repository hashicorp/terraform-ls, pull requests merged in 2020-06, with the labels that each got.

#126 textDocument/didChange: Avoid flagging non-consecutive versions
  langserver/handlers/did_change.go
Labels: bug

#98 Support simplified building and go get
  .github/workflows/release.yml
  .goreleaser.yml
  Makefile
  main.go
  version.go
  version/version.go
Labels: build

#119 Add support for autocomplete based on a prefix
  internal/hcl/errors.go
  internal/hcl/hcl.go
  internal/hcl/hcl_test.go
  internal/hcl/types.go
  internal/lsp/completion.go
  internal/terraform/lang/config_block.go
  internal/terraform/lang/config_block_test.go
  internal/terraform/lang/datasource_block.go
  internal/terraform/lang/datasource_block_test.go
  internal/terraform/lang/hcl_block.go
  internal/terraform/lang/hcl_block_type.go
  internal/terraform/lang/hcl_parser.go
  internal/terraform/lang/hcl_parser_test.go
  internal/terraform/lang/parser.go
  internal/terraform/lang/parser_test.go
  internal/terraform/lang/provider_block.go
  internal/terraform/lang/provider_block_test.go
  internal/terraform/lang/resource_block.go
  internal/terraform/lang/resource_block_test.go
  internal/terraform/lang/types.go
  internal/terraform/lang/utils.go
  langserver/handlers/complete.go
  langserver/handlers/complete_test.go
Labels: textDocument/complete

#131 Add VS Code instructions, sort list alphabetically
  docs/USAGE.md
Labels: documentation

#132 textDocument/complete: Use isIncomplete for >100 items
  internal/terraform/lang/config_block.go
  internal/terraform/lang/config_block_test.go
  internal/terraform/lang/parser.go
Labels: enhancement, textDocument/complete

#133 textDocument/complete: Pass TextEdit instead of static text
  internal/lsp/completion.go
  internal/terraform/lang/config_block.go
  internal/terraform/lang/config_block_test.go
  internal/terraform/lang/parser.go
  internal/terraform/lang/types.go
  internal/terraform/lang/utils.go
Labels: enhancement, textDocument/complete

#134 Make Terraform exec timeout configurable
  commands/serve_command.go
  internal/context/context.go
  internal/terraform/exec/exec.go
  langserver/handlers/service.go
Labels: enhancement

#139 terraform/exec: Pass through all environment variables
  internal/terraform/exec/exec.go
Labels: bug

#143 fix: os.Environ() returns KEY=val, not just keys
  internal/lsp/completion.go
  internal/terraform/exec/exec.go
Labels: bug

#149 terraform: Support 0.13 version
  internal/terraform/errors/errors.go
  internal/terraform/lang/parser.go
  internal/terraform/schema/schema_storage.go
  internal/terraform/schema/schema_storage_test.go
  internal/terraform/schema/watcher.go
Labels: enhancement

#157 Add Hashibot configuration
  .hashibot.hcl
Labels: build

#171 Treat schema availability as not essential
  internal/terraform/errors/errors.go
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
  langserver/handlers/initialize.go
Labels: enhancement

#172 fix detection of single file during initialization
  langserver/handlers/initialize.go
Labels: bug

#178 Make formatting work regardless of initialization state
  internal/terraform/rootmodule/errors.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/types.go
  langserver/handlers/formatting.go
Labels: bug, textDocument/formatting

#182 Display '.' in warning message for top directory
  langserver/handlers/did_open.go
Labels: bug

#183 rootmodule: Fix schema/module update detection
  internal/terraform/rootmodule/root_module.go
Labels: bug

#146 Add `gofmt -s` to CI
  .gitattributes
  .github/workflows/ci.yml
  Makefile
  go.mod
  go.sum
  internal/terraform/lang/config_block_test.go
  tools.go
  vendor/github.com/mh-cbon/go-fmt-fail/.gitignore
  vendor/github.com/mh-cbon/go-fmt-fail/.travis.yml
  vendor/github.com/mh-cbon/go-fmt-fail/.version
  vendor/github.com/mh-cbon/go-fmt-fail/CHANGELOG.md
  vendor/github.com/mh-cbon/go-fmt-fail/LICENSE
  vendor/github.com/mh-cbon/go-fmt-fail/README.md
  vendor/github.com/mh-cbon/go-fmt-fail/appveyor.yml
  vendor/github.com/mh-cbon/go-fmt-fail/change.log
  vendor/github.com/mh-cbon/go-fmt-fail/deb.json
  vendor/github.com/mh-cbon/go-fmt-fail/hasWritten/index.go
  vendor/github.com/mh-cbon/go-fmt-fail/main.go
  vendor/github.com/mh-cbon/go-fmt-fail/rpm.json
  vendor/github.com/mh-cbon/go-fmt-fail/wix.json
  vendor/modules.txt
Labels: build

#197 build: Scope hc-release publish
  .github/workflows/release.yml
Labels: build
