Repository hashicorp/terraform-ls, pull requests merged in 2020-12, with the labels that each got.

#324 Refactor command handlers
  internal/langserver/cmd/cmd.go
  internal/langserver/cmd/cmd_args.go
  internal/langserver/handlers/command/rootmodules.go
  internal/langserver/handlers/execute_command.go
  internal/langserver/handlers/execute_command_rootmodules_test.go
Labels: technical-debt

#329 Display provider versions in completion/hover detail
  go.mod
  go.sum
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/execute_command_init_test.go
  internal/langserver/handlers/formatting_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/hover_test.go
  internal/schemas/gen/gen.go
  internal/schemas/schemas.go
  internal/schemas/version_output.go
  internal/terraform/exec/exec.go
  internal/terraform/exec/exec_test.go
  internal/terraform/exec/mock/executor.go
  internal/terraform/exec/types.go
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/root_module_manager_mock_test.go
  internal/terraform/rootmodule/root_module_manager_test.go
Labels: enhancement

#323 Support Terraform Validate Command
  go.mod
  go.sum
  internal/langserver/diagnostics/diagnostics.go
  internal/langserver/diagnostics/diagnostics_test.go
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/execute_command.go
  internal/langserver/handlers/execute_command_validate_test.go
  internal/terraform/exec/exec.go
  internal/terraform/exec/mock/executor.go
  internal/terraform/exec/types.go
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/types.go
Labels: enhancement

#335 fix: pass dir handler to init command
  internal/langserver/handlers/did_open.go
Labels: bug

#336 Report progress for validate command
  internal/langserver/handlers/command/validate.go
Labels: enhancement
