Repository hashicorp/terraform-ls, pull requests merged in 2020-05, with the labels that each got.

#58 Add support for completing labels
  internal/terraform/lang/config_block.go
  internal/terraform/lang/datasource_block.go
  internal/terraform/lang/datasource_block_test.go
  internal/terraform/lang/hcl_block.go
  internal/terraform/lang/provider_block.go
  internal/terraform/lang/provider_block_test.go
  internal/terraform/lang/resource_block.go
  internal/terraform/lang/resource_block_test.go
  internal/terraform/lang/types.go
  internal/terraform/schema/schema_storage.go
  internal/terraform/schema/schema_storage_mock.go
  internal/terraform/schema/schema_storage_test.go
Labels: enhancement, textDocument/complete

#84 terraform: Report uninitialized workspace
  internal/terraform/errors/errors.go
  internal/terraform/schema/watcher.go
  langserver/handlers/initialize.go
Labels: enhancement

#85 terraform/discovery: Find exe on Windows explicitly
  internal/terraform/discovery/discovery.go
  internal/terraform/discovery/discovery_unix.go
  internal/terraform/discovery/discovery_windows.go
Labels: bug

#99 build: Sign archives checksum
  .github/workflows/main.yml
  .goreleaser.yml
Labels: build

#86 context: Refactor and fix duplicate key
  internal/context/context.go
  internal/context/errors.go
  internal/context/signal_cancel.go
Labels: bug

#102 build: Publish artifacts to releases.hashicorp.com
  .github/workflows/main.yml
  .goreleaser.yml
Labels: build

#104 textDocument/complete: Complete first level keywords
  internal/hcl/errors.go
  internal/hcl/hcl.go
  internal/hcl/hcl_test.go
  internal/source/source.go
  internal/source/source_test.go
  internal/terraform/lang/config_block.go
  internal/terraform/lang/config_block_test.go
  internal/terraform/lang/datasource_block.go
  internal/terraform/lang/hcl_block.go
  internal/terraform/lang/hcl_block_type.go
  internal/terraform/lang/hcl_parser.go
  internal/terraform/lang/hcl_parser_test.go
  internal/terraform/lang/labels.go
  internal/terraform/lang/parser.go
  internal/terraform/lang/parser_test.go
  internal/terraform/lang/provider_block.go
  internal/terraform/lang/resource_block.go
  internal/terraform/lang/schema.go
  internal/terraform/lang/types.go
  langserver/handlers/complete.go
Labels: enhancement

#67 build: Add CI setup
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: build

#115 Improve UX of completion items
  go.mod
  go.sum
  internal/lsp/completion.go
  internal/mdplain/mdplain.go
  internal/mdplain/mdplain_test.go
  internal/terraform/lang/config_block.go
  internal/terraform/lang/config_block_test.go
  internal/terraform/lang/datasource_block.go
  internal/terraform/lang/datasource_block_test.go
  internal/terraform/lang/parser.go
  internal/terraform/lang/parser_test.go
  internal/terraform/lang/provider_block.go
  internal/terraform/lang/provider_block_test.go
  internal/terraform/lang/resource_block.go
  internal/terraform/lang/resource_block_test.go
  internal/terraform/lang/schema.go
  internal/terraform/lang/types.go
  internal/terraform/schema/schema_storage.go
  langserver/handlers/complete_test.go
  vendor/github.com/hashicorp/terraform-json/schemas.go
  vendor/modules.txt
Labels: enhancement, textDocument/complete

#120 langserver: Make requests sequential
  langserver/langserver.go
Labels: enhancement

#103 Partial update
  .gitignore
  internal/filesystem/file.go
  internal/filesystem/file_test.go
  internal/filesystem/filesystem.go
  internal/filesystem/filesystem_test.go
  internal/filesystem/types.go
  internal/lsp/file.go
  internal/lsp/file_change.go
  internal/lsp/file_change_test.go
  langserver/handlers/did_change.go
  langserver/handlers/handlers_test.go
  langserver/handlers/initialize.go
Labels: enhancement
