Repository hashicorp/terraform-ls, pull requests merged in 2020-11, with the labels that each got.

#287 Provide version-aware schema for completion of "core" blocks
  go.mod
  go.sum
  internal/terraform/rootmodule/root_module.go
  langserver/handlers/complete_test.go
Labels: enhancement

#289 Add support for upcoming Terraform v0.14
  internal/terraform/rootmodule/plugin_lock_file.go
Labels: enhancement

#293 Update contribution docs
  .github/CONTRIBUTING.md
Labels: documentation

#298 textDocument/completion: Fix wrong range near EOF
  go.mod
  go.sum
Labels: bug, textDocument/completion

#294 langserver: Implement textDocument/hover
  go.mod
  go.sum
  internal/lsp/hover.go
  langserver/handlers/complete_test.go
  langserver/handlers/handlers_test.go
  langserver/handlers/hover.go
  langserver/handlers/hover_test.go
  langserver/handlers/initialize.go
  langserver/handlers/service.go
Labels: enhancement, textDocument/hover

#300 completion: Prompt picking type of provider/data/resource automatically
  commands/completion_command.go
  go.mod
  go.sum
  internal/lsp/completion.go
  langserver/handlers/complete.go
Labels: enhancement, textDocument/completion

#301 Avoid ignoring schema for uninitialized module
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/root_module_manager_test.go
  internal/terraform/rootmodule/testdata/README.md
  internal/terraform/rootmodule/testdata/uninitialized-root/main.tf
Labels: bug

#307 Avoid panic by initing universal schema early
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/types.go
Labels: bug

#308 Capture editor.action.triggerSuggest to avoid errors
  langserver/handlers/execute_command.go
Labels: bug

#302 Preload providers
  .gitignore
  go.mod
  go.sum
  internal/schemas/doc.go
  internal/schemas/gen/gen.go
  internal/schemas/schemas.go
  internal/terraform/rootmodule/root_module.go
Labels: enhancement

#309 Bump jrpc2 to latest version
  go.mod
  go.sum
Labels: enhancement

#312 Fix provider name/alias mixup
  internal/schemas/gen/gen.go
  internal/schemas/schemas.go
Labels: bug

#313 github: Reflect branch changes
  .github/workflows/ci.yml
Labels: build

#311 Replace sourcegraph/go-lsp with gopls' internal/lsp/protocol
  commands/completion_command.go
  go.mod
  go.sum
  internal/context/context.go
  internal/lsp/completion.go
  internal/lsp/diagnostics.go
  internal/lsp/file.go
  internal/lsp/file_change.go
  internal/lsp/file_handler.go
  internal/lsp/file_handler_test.go
  internal/lsp/file_handler_unix_test.go
  internal/lsp/file_handler_windows_test.go
  internal/lsp/hover.go
  internal/lsp/markup_content.go
  internal/lsp/position.go
  internal/lsp/range.go
  internal/lsp/symbols.go
  internal/lsp/text_edits.go
  internal/protocol/gen.go
  internal/protocol/gen/gen.go
  internal/protocol/protocol.go
  langserver/diagnostics/diagnostics.go
  langserver/handlers/cancel_request.go
  langserver/handlers/complete.go
  langserver/handlers/did_change.go
  langserver/handlers/did_close.go
  langserver/handlers/did_open.go
  langserver/handlers/execute_command.go
  langserver/handlers/execute_command_rootmodules.go
  langserver/handlers/formatting.go
  langserver/handlers/handlers_test.go
  langserver/handlers/hover.go
  langserver/handlers/hover_test.go
  langserver/handlers/initialize.go
  langserver/handlers/initialized.go
  langserver/handlers/service.go
  langserver/handlers/shutdown.go
  langserver/handlers/symbols.go
Labels: enhancement

#318 Expose server version via LSP
  commands/serve_command.go
  internal/context/context.go
  langserver/handlers/handlers_test.go
  langserver/handlers/initialize.go
  langserver/handlers/service.go
Labels: enhancement

#320 fix issue when hoverData is nil
  internal/lsp/hover.go
  langserver/handlers/hover.go
Labels: bug
