Repository hashicorp/terraform-ls, pull requests merged in 2020-07, with the labels that each got.

#199 fix volume case issue in windows platform
  internal/terraform/rootmodule/path.go
  internal/terraform/rootmodule/path_unix_test.go
  internal/terraform/rootmodule/path_windows_test.go
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
Labels: bug

#196 terraform/rootmodule: Make walker async by default
  internal/context/context.go
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/root_module_manager_mock.go
  internal/terraform/rootmodule/root_module_manager_mock_test.go
  internal/terraform/rootmodule/root_module_manager_test.go
  internal/terraform/rootmodule/types.go
  internal/terraform/rootmodule/walker.go
  internal/terraform/rootmodule/walker_mock.go
  internal/terraform/schema/schema_storage.go
  internal/terraform/schema/schema_storage_mock.go
  langserver/handlers/handlers_test.go
  langserver/handlers/initialize.go
  langserver/handlers/service.go
  langserver/handlers/service_mock_test.go
  langserver/langserver_mock.go
Labels: bug

#204 build: print out hc-releases version after installation
  .github/workflows/release.yml
Labels: build

#210 Read go version from .go-version on GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: build

#201 goreleaser: publish Homebrew formula
  .github/workflows/release.yml
  .goreleaser.yml
Labels: build

#216 docs: update links to community forum
  .github/ISSUE_TEMPLATE/config.yml
  .github/SUPPORT.md
Labels: documentation

#215 Readme: recommend installation from Homebrew formula
  README.md
Labels: build

#220 Gate formatting capability on v0.7.7+
  internal/context/context.go
  internal/terraform/exec/exec.go
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/types.go
  langserver/handlers/formatting.go
  langserver/handlers/formatting_test.go
  langserver/handlers/service.go
Labels: bug

#208 Pass -no-color to terraform
  internal/terraform/exec/exec.go
  internal/terraform/exec/exec_test.go
  internal/terraform/rootmodule/root_module_manager_mock_test.go
  internal/terraform/rootmodule/root_module_manager_test.go
  langserver/handlers/complete_test.go
  langserver/handlers/formatting_test.go
  langserver/handlers/handlers_test.go
  langserver/handlers/initialize_test.go
Labels: enhancement, terraform/exec

#223 Introduce CPU & memory profiling
  commands/serve_command.go
  docs/TROUBLESHOOTING.md
Labels: enhancement

#198 settings: Make root modules configurable
  docs/SETTINGS.md
  docs/USAGE.md
  go.mod
  go.sum
  internal/context/context.go
  internal/settings/settings.go
  internal/settings/settings_test.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/types.go
  langserver/handlers/initialize.go
  langserver/handlers/service.go
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: enhancement

#227 Revert "Pass -no-color to terraform"
  internal/terraform/exec/exec.go
  internal/terraform/exec/exec_test.go
  internal/terraform/rootmodule/root_module_manager_mock_test.go
  internal/terraform/rootmodule/root_module_manager_test.go
  langserver/handlers/complete_test.go
  langserver/handlers/formatting_test.go
  langserver/handlers/handlers_test.go
  langserver/handlers/initialize_test.go
Labels: bug

#228 internal/context: make context first argument
  commands/serve_command.go
  internal/context/context.go
  langserver/handlers/service.go
Labels: technical-debt

#229 rootmodule: log errors after loading is finished
  internal/terraform/rootmodule/root_module.go
Labels: technical-debt

#233 Add instructions for LanguageClient-neovim
  docs/USAGE.md
Labels: documentation

#234 Fix some issues observed via staticcheck
  internal/filesystem/file.go
  internal/hcl/hcl.go
  internal/hcl/hcl_test.go
  internal/lsp/file_handler_test.go
  internal/lsp/file_handler_windows_test.go
  internal/terraform/exec/exec.go
  internal/terraform/exec/exec_mock.go
  internal/terraform/lang/datasource_block.go
  internal/terraform/lang/errors.go
  internal/terraform/rootmodule/module_manifest.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/schema/errors.go
  langserver/session/session.go
  logging/logging.go
  version.go
Labels: technical-debt

#236 fix: Prevent parsing invalid tokens
  go.mod
  internal/hcl/hcl.go
  internal/hcl/hcl_test.go
  internal/terraform/lang/parser_test.go
Labels: bug

#239 fix: Append EOF instead of newline
  internal/hcl/hcl.go
  internal/hcl/hcl_test.go
  internal/terraform/lang/config_block.go
  internal/terraform/lang/hcl_block.go
  internal/terraform/lang/hcl_block_type.go
  internal/terraform/lang/hcl_parser_test.go
  internal/terraform/lang/parser_test.go
  internal/terraform/lang/types.go
Labels: bug

#242 ci: Add codecov coverage upload step
  .github/.codecov.yml
  .github/workflows/ci.yml
  .gitignore
  Makefile
Labels: build

#243 terraform/schema: Make schema storage version-aware
  go.mod
  go.sum
  internal/terraform/addrs/provider.go
  internal/terraform/addrs/provider_test.go
  internal/terraform/lang/datasource_block.go
  internal/terraform/lang/datasource_block_test.go
  internal/terraform/lang/provider_block.go
  internal/terraform/lang/provider_block_test.go
  internal/terraform/lang/resource_block.go
  internal/terraform/lang/resource_block_test.go
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/root_module_mock.go
  internal/terraform/schema/schema_storage.go
  internal/terraform/schema/schema_storage_mock.go
  internal/terraform/schema/schema_storage_test.go
  internal/terraform/schema/testdata/null-schema-0.12.json
  internal/terraform/schema/testdata/null-schema-0.13.json
  vendor/github.com/hashicorp/terraform-svchost/LICENSE
  vendor/github.com/hashicorp/terraform-svchost/go.mod
  vendor/github.com/hashicorp/terraform-svchost/go.sum
  vendor/github.com/hashicorp/terraform-svchost/label_iter.go
  vendor/github.com/hashicorp/terraform-svchost/svchost.go
  vendor/golang.org/x/net/AUTHORS
  vendor/golang.org/x/net/CONTRIBUTORS
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/PATENTS
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/golang.org/x/net/idna/tables10.0.0.go
  vendor/golang.org/x/net/idna/tables11.0.0.go
  vendor/golang.org/x/net/idna/tables9.0.0.go
  vendor/golang.org/x/net/idna/trie.go
  vendor/golang.org/x/net/idna/trieval.go
  vendor/golang.org/x/text/encoding/encoding.go
  vendor/golang.org/x/text/encoding/internal/identifier/identifier.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/internal/internal.go
  vendor/golang.org/x/text/encoding/unicode/override.go
  vendor/golang.org/x/text/encoding/unicode/unicode.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/runes/cond.go
  vendor/golang.org/x/text/runes/runes.go
  vendor/golang.org/x/text/secure/bidirule/bidirule.go
  vendor/golang.org/x/text/secure/bidirule/bidirule10.0.0.go
  vendor/golang.org/x/text/secure/bidirule/bidirule9.0.0.go
  vendor/golang.org/x/text/unicode/bidi/bidi.go
  vendor/golang.org/x/text/unicode/bidi/bracket.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/bidi/prop.go
  vendor/golang.org/x/text/unicode/bidi/tables10.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go
  vendor/golang.org/x/text/unicode/bidi/tables9.0.0.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: bug, terraform/0.13

#244 Improve root module discovery error handling
  internal/terraform/rootmodule/root_module.go
  langserver/handlers/did_open.go
Labels: technical-debt

#245 build: Pin codecov Action to v1
  .github/workflows/ci.yml
Labels: build

#231 New command: inspect-module
  commands/inspect_module_command.go
  docs/TROUBLESHOOTING.md
  internal/terraform/rootmodule/root_module.go
  internal/terraform/rootmodule/root_module_manager.go
  internal/terraform/rootmodule/root_module_manager_test.go
  internal/terraform/rootmodule/types.go
  internal/terraform/rootmodule/walker.go
  langserver/handlers/initialize.go
  langserver/handlers/service.go
  main.go
Labels: enhancement

#246 settings: Support relative paths to root modules
  docs/SETTINGS.md
  internal/settings/settings.go
  internal/settings/settings_test.go
  langserver/handlers/did_open.go
  langserver/handlers/did_open_test.go
  langserver/handlers/initialize.go
Labels: enhancement

#247 Support 'homedir' ~ in root module paths
  docs/SETTINGS.md
  go.mod
  go.sum
  langserver/handlers/initialize.go
  vendor/github.com/mitchellh/go-homedir/LICENSE
  vendor/github.com/mitchellh/go-homedir/README.md
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/github.com/mitchellh/go-homedir/homedir.go
  vendor/modules.txt
Labels: enhancement

#248 Warn and skip invalid root module paths
  langserver/handlers/initialize.go
Labels: enhancement
