Repository hashicorp/terraform-ls, pull requests merged in 2021-07, with the labels that each got.

#575 fix: avoid circular references to list/map/object attributes
  go.mod
  go.sum
Labels: bug

#576 Update goreleaser homebrew Git commit information
  .goreleaser.yml
Labels: build

#578 fix: avoid crash on empty file formatting
  internal/hcl/diff.go
  internal/hcl/diff_test.go
Labels: bug

#502 Support multiple folders natively
  internal/cmd/inspect_module_command.go
  internal/langserver/handlers/did_change_workspace_folders.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/state/module.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_manager.go
  internal/terraform/module/module_manager_test.go
  internal/terraform/module/module_ops_queue.go
  internal/terraform/module/types.go
  internal/terraform/module/walker.go
  internal/terraform/module/walker_queue.go
  internal/terraform/module/watcher.go
  internal/terraform/module/watcher_mock.go
Labels: enhancement

#569 Go to attribute/block from reference
  internal/langserver/handlers/go_to_ref_target.go
  internal/langserver/handlers/go_to_ref_target_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/lsp/document_links.go
  internal/lsp/location_links.go
Labels: enhancement, textDocument/declaration, textDocument/definition

#579 fix: increase walker queue buffer & start walking early
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/initialize_test.go
  internal/terraform/module/walker.go
Labels: bug

#572 Go to references (addresses)
  go.mod
  go.sum
  internal/decoder/decoder.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/references.go
  internal/langserver/handlers/references_test.go
  internal/langserver/handlers/service.go
  internal/lsp/locations.go
  internal/state/module.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
Labels: enhancement, textDocument/references

#580 references: use innermost target instead of outermost
  go.mod
  go.sum
  internal/langserver/handlers/references.go
Labels: enhancement, textDocument/references

#582 Make references scope & type aware
  go.mod
  go.sum
Labels: enhancement, textDocument/definition, textDocument/hover, textDocument/references, textDocument/semanticTokens

#587 fix 'go to references' for resources & data sources
  go.mod
  go.sum
Labels: bug

#584 Implement reference count code lens
  docs/language-clients.md
  go.mod
  go.sum
  internal/langserver/handlers/code_lens.go
  internal/langserver/handlers/code_lens_test.go
  internal/langserver/handlers/command/init.go
  internal/langserver/handlers/command/module_callers.go
  internal/langserver/handlers/command/modules.go
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/lsp/range.go
  internal/protocol/experimental.go
Labels: enhancement, textDocument/codeLens

#590 Introduce Defer to module loader
  internal/langserver/handlers/did_open.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_manager.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/types.go
  internal/terraform/module/walker.go
  internal/terraform/module/watcher.go
Labels: enhancement

#551 Add basic module support for variable completion
  .gitignore
  .vscode/launch.json
  go.mod
  go.sum
  internal/state/module.go
  internal/state/state.go
  internal/terraform/module/module_manager.go
  internal/terraform/module/module_ops.go
Labels: enhancement, textDocument/completion, textDocument/hover, textDocument/semanticTokens

#591 Queue decoding of submodules asynchronously
  internal/state/module.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_manager.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/types.go
  internal/terraform/module/walker.go
  internal/terraform/module/watcher.go
Labels: enhancement

#594 fix: recognize references in lists and other complex types
  go.mod
  go.sum
  internal/langserver/handlers/code_lens.go
  internal/langserver/handlers/go_to_ref_target.go
  internal/langserver/handlers/references.go
Labels: bug

#593 Provide module output references
  go.mod
  go.sum
  internal/langserver/handlers/code_lens.go
  internal/langserver/handlers/complete_test.go
  internal/state/module.go
  internal/terraform/exec/exec.go
  internal/terraform/exec/mock/executor.go
  internal/terraform/exec/types.go
Labels: enhancement, textDocument/completion, textDocument/definition, textDocument/hover, textDocument/references

#596 fix: recognize references in common nested expressions
  go.mod
  go.sum
Labels: bug, textDocument/definition, textDocument/references, textDocument/semanticTokens
