Repository hashicorp/terraform-ls, pull requests merged in 2021-11, with the labels that each got.

#689 refactor: Reflect upstream `hcl-lang` changes
  go.mod
  go.sum
  internal/cmd/completion_command.go
  internal/codelens/reference_count.go
  internal/context/context.go
  internal/decoder/context.go
  internal/decoder/decoder.go
  internal/decoder/module_schema.go
  internal/decoder/path_reader.go
  internal/langserver/handlers/code_lens.go
  internal/langserver/handlers/complete.go
  internal/langserver/handlers/document_link.go
  internal/langserver/handlers/go_to_ref_target.go
  internal/langserver/handlers/hover.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/references.go
  internal/langserver/handlers/semantic_tokens.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/symbols.go
  internal/langserver/handlers/workspace_symbol.go
  internal/lsp/client_capabilities.go
  internal/lsp/client_name.go
  internal/lsp/command.go
  internal/lsp/location_links.go
  internal/lsp/locations.go
  internal/lsp/symbols.go
  internal/state/module.go
  internal/terraform/module/builtin_references.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_manager.go
  internal/terraform/module/module_manager_test.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/types.go
Labels: enhancement

#696 Implement ignorelist for module indexing
  docs/SETTINGS.md
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/initialize_test.go
  internal/settings/settings.go
  internal/settings/settings_test.go
  internal/terraform/module/walker.go
Labels: enhancement

#698 terraform/module: fix reference collection skipping
  internal/state/module.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_loader_test.go
  internal/terraform/module/testdata/single-root-no-modules/main.tf
Labels: bug

#697 Implement support for JSON variable files
  internal/terraform/ast/variables.go
  internal/terraform/parser/variables.go
Labels: enhancement

#707 fix: Avoid crash in telemetry on module removal
  internal/langserver/handlers/did_change_workspace_folders_test.go
  internal/langserver/handlers/hooks_module.go
  internal/langserver/handlers/service.go
Labels: bug

#714 refactor: decouple diagnostics from handlers into a hook
  internal/langserver/diagnostics/diagnostics.go
  internal/langserver/diagnostics/diagnostics_test.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_close.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/hooks_module.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/langserver/session/types.go
  internal/state/module.go
  internal/terraform/module/module_loader_test.go
  internal/terraform/module/module_manager.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/types.go
  internal/terraform/module/walker.go
  internal/terraform/module/watcher.go
Labels: bug, enhancement, textDocument/publishDiagnostics

#699 Avoid duplicate state entries (by avoiding symlink evaluation)
  internal/langserver/handlers/initialize.go
  internal/terraform/module/module_manager.go
Labels: bug

#700 Introduce go-to-variable from module input name
  .github/workflows/ci.yml
  go.mod
  go.sum
  internal/codelens/reference_count.go
  internal/decoder/decoder.go
  internal/langserver/handlers/code_lens.go
  internal/langserver/handlers/code_lens_test.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/go_to_ref_target.go
  internal/langserver/handlers/go_to_ref_target_test.go
  internal/langserver/handlers/hooks_module.go
  internal/langserver/handlers/references.go
  internal/langserver/handlers/references_test.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/testdata/single-submodule/.terraform/modules/modules.json
  internal/langserver/handlers/testdata/single-submodule/application/main.tf
  internal/langserver/handlers/testdata/single-submodule/main.tf
  internal/langserver/handlers/testdata/single-submodule/terraform.tfvars
  internal/lsp/location_links.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_loader_test.go
  internal/terraform/module/walker.go
  internal/terraform/module/watcher.go
Labels: enhancement

#729 Update neovim formatting example to use the sync version
  docs/USAGE.md
Labels: documentation
