Repository hashicorp/terraform-ls, pull requests merged in 2021-06, with the labels that each got.

#538 Migrate from GitHub HashiBot to GitHub Actions
  .github/workflows/issue-comment-created.yml
  .github/workflows/lock.yml
  .github/workflows/stale.yml
  .hashibot.hcl
Labels: build

#540 Add support for `tfvars` (variable files)
  go.mod
  go.sum
  internal/cmd/completion_command.go
  internal/cmd/inspect_module_command.go
  internal/decoder/decoder.go
  internal/langserver/handlers/complete.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/document_link.go
  internal/langserver/handlers/document_link_test.go
  internal/langserver/handlers/formatting_test.go
  internal/langserver/handlers/hover.go
  internal/langserver/handlers/hover_test.go
  internal/langserver/handlers/semantic_tokens.go
  internal/langserver/handlers/semantic_tokens_test.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/symbols.go
  internal/lsp/language_id.go
  internal/state/module.go
  internal/state/module_test.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_manager.go
  internal/terraform/module/module_manager_test.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
  internal/terraform/module/types.go
Labels: enhancement, textDocument/completion, textDocument/hover, textDocument/semanticTokens

#545 Bump hashicorp/terraform-schema to 8f289892
  go.mod
  go.sum
  internal/langserver/handlers/complete_test.go
  internal/state/provider_schema_test.go
Labels: enhancement

#544 Add support for state backends
  go.mod
  go.sum
  internal/terraform/module/module_manager.go
Labels: enhancement, textDocument/completion, textDocument/hover, textDocument/semanticTokens

#542 Add support for provisioners
  go.mod
  go.sum
Labels: enhancement, textDocument/completion, textDocument/hover, textDocument/semanticTokens

#546 Bump `terraform-schema`
  go.mod
  go.sum
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/hover_test.go
Labels: enhancement, textDocument/completion, textDocument/hover

#543 Support variable `default`
  internal/terraform/module/module_manager.go
Labels: enhancement, textDocument/completion, textDocument/hover, textDocument/semanticTokens

#547 docs: Add notes for language clients
  docs/language-clients.md
Labels: documentation

#553 Support for references to vars and locals
  go.mod
  go.sum
Labels: enhancement, textDocument/completion, textDocument/hover, textDocument/semanticTokens

#555 Prevent var names from being completed in label
  go.mod
  go.sum
Labels: bug, textDocument/completion

#561 Mock out code lens support
  internal/langserver/handlers/code_lens.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
Labels: bug, textDocument/codeLens

#568 .github/workflows: Switch release workflow to setup-hc-releases action
  .github/workflows/release.yml
Labels: build

#566 Provide (less verbose) step-based completion
  go.mod
  go.sum
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
Labels: enhancement, textDocument/completion

#570 refactoring: Reference -> ReferenceTargets
  go.mod
  go.sum
  internal/decoder/decoder.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_open.go
  internal/state/module.go
  internal/terraform/module/builtin_references.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
Labels: technical-debt
