Repository hashicorp/terraform-ls, pull requests merged in 2021-08, with the labels that each got.

#601 textDocument/publishDiagnostics: Publish any source-less warnings or errors
  internal/langserver/diagnostics/validate_diags.go
Labels: bug, textDocument/publishDiagnostics

#603 fix: avoid publishing stale 'validate' diagnostics
  internal/context/context.go
  internal/langserver/diagnostics/diagnostics.go
  internal/langserver/diagnostics/diagnostics_test.go
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/service.go
Labels: bug

#605 fix: avoid crash on highlighting unknown tuple element
  go.mod
  go.sum
Labels: bug

#607 fix: recognize list(object) and set(object) attributes as blocks
  go.mod
  go.sum
Labels: bug

#602 Always validate URI schema
  internal/langserver/handlers/command/init.go
  internal/langserver/handlers/command/module_callers.go
  internal/langserver/handlers/command/validate.go
  internal/lsp/file_handler_unix_test.go
  internal/uri/uri.go
  internal/uri/uri_test.go
Labels: enhancement

#610 fix: allow multiple variable validation blocks
  go.mod
  go.sum
Labels: bug

#608 Bump LSP structs to gopls 0.7.0
  internal/cmd/completion_command.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/workspace_symbol.go
  internal/lsp/range.go
  internal/lsp/symbols.go
  internal/lsp/token_encoder.go
  internal/lsp/token_encoder_test.go
  internal/protocol/gen/gen.go
  internal/protocol/protocol.go
Labels: dependencies

#612 fix: avoid crash on missing block label
  go.mod
  go.sum
Labels: bug

#615 github: Reduce jobs timeout from high default
  .github/workflows/ci.yml
Labels: build

#616 github: Update docs about providers
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#622 ci: Use latest versions of (Windows/macOS/Ubuntu)
  .github/workflows/ci.yml
Labels: build

#625 Format on save code action
  docs/language-clients.md
  internal/langserver/handlers/code_action.go
  internal/langserver/handlers/code_action_test.go
  internal/langserver/handlers/formatting.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/lsp/code_actions.go
Labels: enhancement, textDocument/codeAction

#627 ci: Automate milestone closing & commenting
  .github/workflows/milestone-closed.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: build

#628 fix: Limit label completion items to 100
  go.mod
  go.sum
Labels: bug

#621 Support standalone (not autoloaded) `*.tfvars` files
  .gitattributes
  internal/decoder/decoder.go
  internal/filesystem/filesystem.go
  internal/filesystem/filesystem_test.go
  internal/filesystem/types.go
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_close.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/service.go
  internal/state/module.go
  internal/state/module_test.go
  internal/terraform/ast/ast.go
  internal/terraform/ast/ast_test.go
  internal/terraform/ast/module.go
  internal/terraform/ast/variables.go
  internal/terraform/module/module_ops.go
  internal/terraform/parser/module.go
  internal/terraform/parser/module_test.go
  internal/terraform/parser/parser.go
  internal/terraform/parser/testdata/empty-dir/.gitkeep
  internal/terraform/parser/testdata/invalid-mod-files/incomplete-block.tf
  internal/terraform/parser/testdata/invalid-mod-files/missing-brace.tf
  internal/terraform/parser/testdata/valid-mod-files-with-extra-items/.hidden.tf
  internal/terraform/parser/testdata/valid-mod-files-with-extra-items/main.tf
  internal/terraform/parser/testdata/valid-mod-files-with-extra-items/main.tf~
  internal/terraform/parser/testdata/valid-mod-files/empty.tf
  internal/terraform/parser/testdata/valid-mod-files/resources.tf
  internal/terraform/parser/variables.go
Labels: enhancement
