Repository hashicorp/terraform-ls, pull requests merged in 2022-02, with the labels that each got.

#780 Ignore window binary from local builds
  .gitignore
Labels: build

#788 schemas: Ignore jradtilbrook/buildkite
  internal/schemas/gen/gen.go
Labels: build

#630 Enable Semantic Token Refresh
  internal/langserver/handlers/hooks_module.go
  internal/langserver/handlers/service.go
  internal/state/module.go
Labels: enhancement, workspace/semanticTokens

#789 Add String() for `OpTypeDecodeVarsReferences`
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
Labels: enhancement

#802 Update semantic token block label type
  internal/langserver/handlers/semantic_tokens_test.go
  internal/lsp/token_encoder.go
  internal/lsp/token_encoder_test.go
  internal/lsp/token_types.go
Labels: enhancement, textDocument/semanticTokens, workspace/semanticTokens

#798 goreleaser: Enable pre-release publishing
  .goreleaser.yml
Labels: build

#799 Fix validate on save
  internal/langserver/handlers/service.go
Labels: bug, textDocument/didSave

#807 Update help for `serve` command arguments
  internal/cmd/serve_command.go
Labels: bug

#806 langserver: gate semantic token refresh on capability
  internal/langserver/handlers/service.go
Labels: bug

#808 deps: Bump hashicorp/terraform-schema to faadc57bd40a
  go.mod
  go.sum
Labels: enhancement, dependencies, modules

#783 Remove go-getter & simplify module source detection
  go.mod
  go.sum
  internal/terraform/datadir/module_types.go
Labels: technical-debt
