Repository hashicorp/terraform-ls, pull requests merged in 2022-08, with the labels that each got.

#1017 Add hooks for dynamic completion
  go.mod
  go.sum
  internal/decoder/decoder.go
  internal/hooks/hooks.go
  internal/hooks/module_source_local.go
  internal/langserver/handlers/complete.go
  internal/langserver/handlers/completion_hooks.go
  internal/langserver/handlers/completion_resolve.go
  internal/langserver/handlers/completion_resolve_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/lsp/completion.go
  internal/lsp/text_edits.go
  internal/protocol/completion.go
  internal/terraform/module/module_ops.go
Labels: enhancement

#1022 schemas: log exec path to Terraform
  internal/schemas/gen/gen.go
Labels: enhancement

#1016 Add terraform version command
  docs/commands.md
  internal/langserver/handlers/command/terraform.go
  internal/langserver/handlers/execute_command.go
  internal/langserver/handlers/execute_command_terraform_version_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/protocol/experimental.go
Labels: enhancement

#1021 state: Introduce `DependsOn` for N-to-1 job dependencies
  internal/indexer/document_change.go
  internal/indexer/module_calls.go
  internal/indexer/walker.go
  internal/indexer/watcher.go
  internal/job/job.go
  internal/scheduler/scheduler_test.go
  internal/state/job_id_slice_index.go
  internal/state/jobs.go
  internal/state/jobs_test.go
  internal/state/module.go
  internal/state/slice_length_index.go
  internal/state/state.go
  internal/walker/walker.go
Labels: enhancement

#1014 Parse provider versions from lock file before obtaining schema
  internal/indexer/walker.go
  internal/indexer/watcher.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/did_change_watched_files_test.go
  internal/langserver/handlers/document_link_test.go
  internal/langserver/handlers/execute_command_module_providers_test.go
  internal/langserver/handlers/go_to_ref_target_test.go
  internal/langserver/handlers/testdata/single-fake-provider/main.tf
  internal/state/module.go
  internal/state/module_test.go
  internal/state/provider_schema.go
  internal/state/provider_schema_test.go
  internal/state/state.go
  internal/terraform/datadir/module_manifest.go
  internal/terraform/datadir/paths.go
  internal/terraform/datadir/plugin_lock_file.go
  internal/terraform/datadir/plugin_lock_file_test.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
  internal/walker/walker_test.go
Labels: enhancement

#1030 fix: bump terraform-schema to fix crash on invalid provider name
  go.mod
  go.sum
Labels: bug

#1027 Pick core schema only based on `required_version` constraint
  go.mod
  go.sum
  internal/decoder/module_schema.go
  internal/indexer/document_open.go
  internal/indexer/walker.go
  internal/indexer/watcher.go
  internal/langserver/handlers/code_action_test.go
  internal/langserver/handlers/code_lens_test.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/did_change_test.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/did_open_test.go
  internal/langserver/handlers/document_link_test.go
  internal/langserver/handlers/execute_command_init_test.go
  internal/langserver/handlers/execute_command_module_callers_test.go
  internal/langserver/handlers/execute_command_module_providers_test.go
  internal/langserver/handlers/execute_command_modules_test.go
  internal/langserver/handlers/execute_command_test.go
  internal/langserver/handlers/execute_command_validate_test.go
  internal/langserver/handlers/formatting_test.go
  internal/langserver/handlers/go_to_ref_target_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/hover_test.go
  internal/langserver/handlers/references_test.go
  internal/langserver/handlers/semantic_tokens_test.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/symbols_test.go
  internal/langserver/handlers/workspace_symbol_test.go
  internal/state/jobs.go
Labels: enhancement

#1006 indexer/walker: Avoid running jobs where not needed
  .github/gobenchdata-checks.yml
  .github/workflows/benchmarks.yml
  internal/indexer/document_change.go
  internal/indexer/document_open.go
  internal/indexer/module_calls.go
  internal/indexer/walker.go
  internal/indexer/watcher.go
  internal/job/ignore_state.go
  internal/job/job.go
  internal/scheduler/scheduler.go
  internal/scheduler/scheduler_test.go
  internal/state/jobs.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
Labels: enhancement

#1036 docs: Update benchmarks
  docs/benchmarks.md
Labels: documentation

#1034 textDocument/formatting: log terraform fmt execution time
  internal/langserver/handlers/code_action.go
  internal/langserver/handlers/formatting.go
Labels: enhancement

#1024 Complete module `source` and `version`
  .github/workflows/release.yml
  .goreleaser.yml
  algolia.go
  go.mod
  go.sum
  internal/algolia/algolia.go
  internal/cmd/serve_command.go
  internal/hooks/hooks.go
  internal/hooks/module_source_local.go
  internal/hooks/module_source_local_test.go
  internal/hooks/module_source_registry.go
  internal/hooks/module_source_registry_test.go
  internal/hooks/module_version.go
  internal/hooks/module_version_test.go
  internal/langserver/handlers/completion_hooks.go
  internal/lsp/completion.go
  internal/registry/registry.go
  internal/registry/registry_test.go
  internal/state/module.go
  main.go
Labels: enhancement

#1037 schemas: exclude oci from schema generation
  .goreleaser.yml
  internal/schemas/gen/gen.go
Labels: ci

#1038 cleanup: Remove LogHandler
  internal/langserver/handlers/log_handler.go
Labels: technical-debt

#1039 clean/ci: avoid running tests via GoReleaser & remove GO111MODULE
  .goreleaser.yml
Labels: ci

#1044 docs: Add link to post explaining vim plugin installation
  docs/USAGE.md
Labels: documentation

#1043 goreleaser: Use correct ldflag (versionPrerelease) when compiling LS
  .goreleaser.yml
Labels: bug, ci

#1048 Fix panic on obtaining provider schemas
  internal/state/provider_schema.go
  internal/state/provider_schema_test.go
Labels: bug

#1049 fix: flaky exit handler test
  internal/langserver/handlers/exit_test.go
Labels: bug

#1046 Bump to Go version stanza to `1.18`, bump hcl-lang to `1fce4f`, terraform-schema to `0778c5`
  .go-version
  go.mod
  go.sum
  internal/langserver/handlers/handlers_test.go
Labels: dependencies
