Repository hashicorp/terraform-ls, pull requests merged in 2022-06, with the labels that each got.

#940 langserver: ignore duplicate document versions in textDocument/didChange
  internal/langserver/handlers/did_change.go
Labels: bug

#939 ci: update benchmark thresholds
  .github/gobenchdata-checks.yml
Labels: ci

#942 goreleaser: Remove brew publishing
  .goreleaser.yml
Labels: ci

#943 docs: revamp Troubleshooting section
  docs/TROUBLESHOOTING.md
  docs/images/sublime-text-cmd-palette-log.png
  docs/images/sublime-text-cmd-palette-settings.png
  docs/images/sublime-text-log-panel.png
  docs/images/sublime-text-settings.png
  docs/images/vscode-json-ls-settings.png
  docs/images/vscode-open-settings-json.png
  docs/images/vscode-output-pane.png
  docs/images/vscode-view-output-menu.png
Labels: documentation

#945 main: allow version metadata to be set
  version.go
Labels: enhancement

#951 handlers/command: Return partially parsed metadata from `module.providers`
  internal/langserver/handlers/command/module_providers.go
Labels: bug

#947 deps: bump LSP structs to gopls 0.8.4
  internal/langserver/handlers/code_action.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/initialize.go
  internal/protocol/gen/gen.go
  internal/protocol/protocol.go
Labels: dependencies

#953 Replace internal watcher with LSP's watching mechanism
  go.mod
  go.sum
  internal/context/context.go
  internal/langserver/handlers/did_change_watched_files.go
  internal/langserver/handlers/did_change_watched_files_test.go
  internal/langserver/handlers/did_change_workspace_folders.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/initialize_benchmarks_test.go
  internal/langserver/handlers/initialized.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/session_mock_test.go
  internal/langserver/handlers/testdata/uninitialized-single-submodule/.gitignore
  internal/langserver/handlers/testdata/uninitialized-single-submodule/application/main.tf
  internal/langserver/handlers/testdata/uninitialized-single-submodule/main.tf
  internal/terraform/datadir/paths.go
  internal/terraform/module/indexer.go
  internal/terraform/module/module_manager_test.go
  internal/terraform/module/walker.go
  internal/terraform/module/watcher.go
  internal/terraform/module/watcher_mock.go
  internal/terraform/module/watcher_test.go
Labels: enhancement

#924 Provide completion, hover and docs links for uninitialized Registry modules
  go.mod
  go.sum
  internal/decoder/path_reader.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/session_mock_test.go
  internal/registry/registry.go
  internal/registry/registry_mock_responses_test.go
  internal/registry/registry_test.go
  internal/registry/types.go
  internal/state/errors.go
  internal/state/module.go
  internal/state/module_test.go
  internal/state/registry_modules.go
  internal/state/registry_modules_test.go
  internal/state/state.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_mock_responses.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
  internal/terraform/module/testdata/uninitialized-external-module/main.tf
  internal/terraform/module/testdata/uninitialized-multiple-external-modules/main.tf
Labels: enhancement

#968 fix: avoid ignoring hidden tfvars files
  internal/terraform/ast/ast.go
  internal/terraform/ast/module.go
  internal/terraform/ast/variables.go
Labels: bug

#965 ci: reduce benchmark minimum threshold for GKE module
  .github/gobenchdata-checks.yml
Labels: ci

#969 fix: avoid crash on invalid URIs
  internal/langserver/handlers/did_change_workspace_folders.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/initialize.go
Labels: bug

#978 walker: remove last occurence of old watcher
  internal/terraform/module/types.go
  internal/terraform/module/walker.go
Labels: technical-debt

#975 ci: lower benchmark threshold for k8s-dashboard
  .github/gobenchdata-checks.yml
Labels: ci

#971 Provide basic IntelliSense (except for diagnostics) for hidden `*.tf` files
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/hooks_module.go
  internal/terraform/ast/ast_test.go
  internal/terraform/ast/module.go
  internal/terraform/ast/variables.go
  internal/terraform/parser/module_test.go
Labels: enhancement

#977 job: Introduce explicit priority for jobs
  internal/job/job.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/indexers.go
  internal/langserver/handlers/service.go
  internal/scheduler/scheduler.go
  internal/scheduler/scheduler_test.go
  internal/state/jobs.go
  internal/state/jobs_test.go
  internal/state/priority_index.go
  internal/state/state.go
  internal/terraform/module/module_manager_test.go
Labels: bug
