Repository hashicorp/terraform-ls, pull requests merged in 2022-10, with the labels that each got.

#1071 schemas: Break down schema generation
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .goreleaser.yml
  internal/indexer/document_change.go
  internal/indexer/module_calls.go
  internal/indexer/walker.go
  internal/langserver/handlers/service.go
  internal/registry/module.go
  internal/registry/module_mock_responses_test.go
  internal/registry/module_test.go
  internal/registry/provider.go
  internal/registry/provider_test.go
  internal/registry/registry.go
  internal/registry/types.go
  internal/schemas/.gitignore
  internal/schemas/data/git.keep
  internal/schemas/gen/gen.go
  internal/schemas/preload_schemas.go
  internal/schemas/schemas.go
  internal/schemas/schemas_preloadschema.go
  internal/schemas/version_output.go
  internal/state/module.go
  internal/state/provider_schema.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
Labels: enhancement

#1081 schemas: Treat legacy providers as hashicorp or builtin
  internal/indexer/document_change.go
  internal/indexer/module_calls.go
  internal/indexer/walker.go
  internal/schemas/schemas.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
Labels: bug

#1082 Update `setup-go` to obtain version via `go-version-file`
  .github/workflows/benchmarks.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: technical-debt

#1084 state: avoid infinite recursion in JobStore
  .github/workflows/nightly-tests.yml
  internal/scheduler/scheduler_long_test.go
  internal/state/jobs.go
Labels: bug

#1086 decoder: fix race condition in terraform-schema SchemaMerger
  go.mod
  go.sum
  internal/decoder/decoder_test.go
  internal/schemas/schemas.go
Labels: bug

#1091 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1092 schemas: remove log statements
  internal/schemas/schemas.go
Labels: bug, ci

#1099 deps: bump hcl-lang to `b20d6288c7f3`
  go.mod
  go.sum
Labels: bug

#1105 Support `each.*` references in blocks with `for_each`
  CHANGELOG.md
  go.mod
  go.sum
Labels: enhancement
