Repository hashicorp/terraform-ls, pull requests merged in 2022-05, with the labels that each got.

#907 ci: Output benchmark results as markdown table
  .github/workflows/benchmarks.yml
  results.json
Labels: ci

#900 Decode module calls (for uninitialized modules)
  go.mod
  go.sum
  internal/decoder/module_schema.go
  internal/decoder/path_reader.go
  internal/state/module.go
  internal/state/state.go
  internal/terraform/module/watcher.go
Labels: enhancement, modules

#909 Subscribe to updates of module.calls data
  docs/language-server.md
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/hooks_module.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/protocol/experimental.go
Labels: enhancement

#842 Onboard to RelAPI
  .github/workflows/release.yml
  .goreleaser.yml
  .release/release-metadata.hcl
Labels: ci

#918 ci: fix reference to gobenchdata
  .github/workflows/benchmarks.yml
Labels: bug, ci

#923 Add utm parameters to `module.*` commands
  internal/decoder/decoder.go
  internal/langserver/handlers/command/docs_url.go
  internal/langserver/handlers/command/handler.go
  internal/langserver/handlers/command/module_calls.go
  internal/langserver/handlers/command/module_calls_test.go
  internal/langserver/handlers/command/module_providers.go
  internal/langserver/handlers/execute_command.go
  internal/langserver/handlers/execute_command_module_providers_test.go
  internal/langserver/handlers/service.go
  internal/utm/utm.go
Labels: enhancement

#790 internal/service: add support for didChangeWatchedFiles
  internal/langserver/handlers/did_change_watched_files.go
  internal/langserver/handlers/did_change_watched_files_test.go
  internal/langserver/handlers/did_change_workspace_folders.go
  internal/langserver/handlers/service.go
Labels: enhancement, workspace/didChangeWatchedFiles

#931 Batch module change events
  internal/langserver/handlers/hooks_module.go
  internal/langserver/handlers/service.go
  internal/langserver/notifier/notifier.go
  internal/langserver/notifier/notifier_test.go
  internal/state/documents.go
  internal/state/hooks.go
  internal/state/jobs.go
  internal/state/module.go
  internal/state/module_changes.go
  internal/state/module_changes_test.go
  internal/state/state.go
  internal/state/time_field_index.go
Labels: enhancement, technical-debt

#933 docs: Document watched files
  docs/language-clients.md
Labels: documentation
