Repository hashicorp/terraform-ls, pull requests merged in 2022-04, with the labels that each got.

#847 docs: remove `rootmodule` cmd from docs
  docs/commands.md
Labels: documentation

#839 walker: Use memdb for queued paths
  internal/cmd/inspect_module_command.go
  internal/context/context.go
  internal/langserver/handlers/cancel_request_test.go
  internal/langserver/handlers/code_action_test.go
  internal/langserver/handlers/code_lens_test.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/did_change_test.go
  internal/langserver/handlers/did_change_workspace_folders.go
  internal/langserver/handlers/did_change_workspace_folders_test.go
  internal/langserver/handlers/did_open_test.go
  internal/langserver/handlers/document_link_test.go
  internal/langserver/handlers/execute_command_init_test.go
  internal/langserver/handlers/execute_command_module_callers_test.go
  internal/langserver/handlers/execute_command_module_providers_test.go
  internal/langserver/handlers/execute_command_modules_test.go
  internal/langserver/handlers/go_to_ref_target_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/hover_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/initialize_test.go
  internal/langserver/handlers/references_test.go
  internal/langserver/handlers/semantic_tokens_test.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/session_mock_test.go
  internal/langserver/handlers/symbols_test.go
  internal/langserver/handlers/workspace_symbol_test.go
  internal/state/documents.go
  internal/state/errors.go
  internal/state/path_state_string.go
  internal/state/state.go
  internal/state/walker_paths.go
  internal/state/walker_paths_test.go
  internal/terraform/module/module_manager_test.go
  internal/terraform/module/types.go
  internal/terraform/module/walker.go
  internal/terraform/module/walker_collector.go
  internal/terraform/module/walker_mock.go
Labels: bug

#852 cmd: Remove `completion` CLI command
  internal/cmd/completion_command.go
  main.go
Labels: technical-debt

#849 Add files to ModuleMetadata
  go.mod
  go.sum
  internal/decoder/module_schema.go
  internal/state/module.go
Labels: enhancement

#851 fix: Ensure loading of parent directory after lower level directories works
  internal/state/documents.go
  internal/state/documents_test.go
  internal/state/jobs.go
  internal/state/state.go
Labels: bug

#853 github: Update message for milestone closure
  .github/workflows/milestone-closed.yml
Labels: ci

#858 github: Add CODEOWNERS file
  .github/CODEOWNERS
Labels: ci

#843 Enable opening a single Terraform file
  docs/SETTINGS.md
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/settings/settings.go
Labels: enhancement

#840 Job scheduler benchmarks
  .github/gobenchdata-checks.yml
  .github/workflows/benchmarks.yml
  docs/benchmarks.md
  go.mod
  go.sum
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize_benchmarks_test.go
  internal/langserver/handlers/testdata/single-module-aws/main.tf
  internal/langserver/handlers/testdata/single-module-no-provider/main.tf
  internal/langserver/handlers/testdata/single-module-random/main.tf
  internal/langserver/langserver_mock.go
  tools.go
Labels: documentation

#863 ci: bump google-network & awk-eks benchmark thresholds
  .github/gobenchdata-checks.yml
Labels: ci

#870 ci: reduce min threshold for k8s-metrics-server benchmark
  .github/gobenchdata-checks.yml
Labels: ci

#875 schemas: Exclude harness/harness-platform from embedding
  internal/schemas/gen/gen.go
Labels: ci

#876 Fix corrupted diffs in formatting responses
  internal/hcl/diff.go
  internal/hcl/diff_test.go
  internal/langserver/handlers/formatting_test.go
Labels: bug, textDocument/formatting

#872 Fix module calls command for remote modules
  internal/langserver/handlers/command/module_calls.go
  internal/langserver/handlers/command/module_calls_test.go
  internal/terraform/datadir/module_types.go
Labels: bug

#879 ci: adjust benchmarks
  .github/gobenchdata-checks.yml
  .github/workflows/benchmarks.yml
Labels: ci

#888 ci: adjust min & max for benchmarks
  .github/gobenchdata-checks.yml
Labels: ci

#891 Use terraform-registry-address for parsing module sources
  go.mod
  go.sum
  internal/terraform/datadir/module_types.go
Labels: enhancement

#874 Add version to module calls
  go.mod
  go.sum
  internal/state/module.go
Labels: enhancement

#901 schemas: Exclude logicmonitor/logicmonitor from embedding
  internal/schemas/gen/gen.go
Labels: ci
