Repository hashicorp/terraform-ls, pull requests merged in 2022-07, with the labels that each got.

#983 deps: bump terraform-schema to e05b3dd5db1d
  go.mod
  go.sum
Labels: enhancement

#988 indexer: refactor & improve/cleanup error handling
  internal/indexer/document_change.go
  internal/indexer/indexer.go
  internal/indexer/module_calls.go
  internal/indexer/walker.go
  internal/indexer/watcher.go
  internal/job/job.go
  internal/job/job_store.go
  internal/scheduler/scheduler.go
  internal/scheduler/scheduler_test.go
  internal/state/jobs_test.go
  internal/walker/walker_collector.go
Labels: technical-debt

#998 deps: bump terraform-schema to 408b2ae
  go.mod
  go.sum
Labels: enhancement

#997 walker: Index uninitialized modules
  go.mod
  go.sum
  internal/cmd/inspect_module_command.go
  internal/indexer/module_calls.go
  internal/indexer/walker.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/did_change_watched_files_test.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/testdata/uninitialized-single-submodule/application/main.tf
  internal/langserver/handlers/testdata/uninitialized-single-submodule/main.tf
  internal/state/module.go
  internal/state/module_test.go
  internal/terraform/ast/module.go
  internal/terraform/datadir/module_manifest.go
  internal/terraform/datadir/module_manifest_test.go
  internal/terraform/datadir/module_manifest_unix_test.go
  internal/terraform/datadir/module_manifest_windows_test.go
  internal/walker/walker.go
  internal/walker/walker_test.go
Labels: enhancement

#1004 docs: Clarify usage of workspaces
  docs/USAGE.md
Labels: documentation

#1007 Enable go to module output declaration from reference
  go.mod
  go.sum
Labels: enhancement

#1003 settings: repurpose indexer-related options
  docs/SETTINGS.md
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/initialize_test.go
  internal/settings/settings.go
  internal/settings/settings_test.go
  internal/walker/walker.go
Labels: technical-debt

#1009 settings: decode deprecated ignoreDirectoryNames & warn
  internal/langserver/handlers/initialize.go
  internal/settings/settings.go
Labels: enhancement, technical-debt

#1010 settings: break down indexing options
  docs/SETTINGS.md
  docs/language-clients.md
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/initialize_test.go
  internal/settings/settings.go
  internal/settings/settings_test.go
Labels: enhancement, technical-debt

#1013 schemas: Improve logging & ignoring when generating schemas
  internal/schemas/gen/gen.go
Labels: enhancement

#1011 settings: break down terraform CLI related settings
  docs/SETTINGS.md
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/settings/settings.go
  internal/settings/settings_test.go
Labels: enhancement, technical-debt

#1012 cmd/serve: Remove deprecated `-tf-exec-*` CLI flags
  internal/cmd/serve_command.go
  internal/langserver/handlers/service.go
Labels: technical-debt

#999 Update usage doc supported filetypes and neovim docs
  docs/USAGE.md
Labels: documentation
