Repository hashicorp/terraform-ls, pull requests merged in 2022-01, with the labels that each got.

#757 fix: avoid code lens updates when disabled
  internal/langserver/handlers/service.go
Labels: bug

#755 fix: Catch OS agnostic interrupt signal
  internal/cmd/inspect_module_command.go
  internal/cmd/serve_command.go
Labels: bug

#737 Switch to hc-install from tfinstall
  go.mod
  go.sum
  internal/langserver/handlers/complete_test.go
  internal/schemas/gen/gen.go
  internal/terraform/exec/exec_test.go
Labels: enhancement, technical-debt

#758 telemetry: Only send requests if data has changed
  internal/langserver/handlers/hooks_module.go
  internal/state/installed_providers.go
  internal/state/installed_providers_test.go
  internal/state/module.go
Labels: bug

#759 fix: Return correct target selection range for definition/declaration
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/go_to_ref_target.go
  internal/langserver/handlers/go_to_ref_target_test.go
  internal/langserver/handlers/service.go
  internal/lsp/location_links.go
  internal/state/provider_schema.go
Labels: bug

#727 Introduce go-to-variable from `tfvars` files
  internal/decoder/decoder.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_open.go
  internal/state/module.go
  internal/state/module_test.go
  internal/terraform/module/module_loader.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/operation/operation.go
  internal/terraform/module/walker.go
  internal/terraform/module/watcher.go
Labels: enhancement, textDocument/definition
