Repository hashicorp/terraform-ls, pull requests merged in 2022-09, with the labels that each got.

#1060 fix: Add missing provider schema versions
  internal/langserver/handlers/execute_command_terraform_version_test.go
  internal/state/module.go
  internal/state/module_changes_test.go
  internal/state/module_test.go
  internal/state/provider_schema.go
  internal/state/provider_schema_test.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
Labels: bug

#1062 Don't query the TF registry for module sources starting with "."
  .gitignore
  internal/hooks/module_source_registry.go
  internal/hooks/module_source_registry_test.go
Labels: enhancement

#1064 ci: bump benchmark thresholds
  .github/gobenchdata-checks.yml
  .github/workflows/benchmarks.yml
Labels: ci

#1057 Handle Invalid WSL URIs
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/initialize_test.go
  internal/uri/uri.go
  internal/uri/uri_test.go
Labels: enhancement

#1070 schemas/cleanup: replace vsfsgen w/ Go stdlib's embed
  go.mod
  go.sum
  internal/schemas/gen/gen.go
  internal/schemas/schemas_preloadschema.go
Labels: technical-debt

#1069 ci: bump benchmark thresholds
  .github/gobenchdata-checks.yml
Labels: ci
