Repository hashicorp/terraform-ls, pull requests merged in 2023-04, with the labels that each got.

#1237 deps: Bump hcl-lang & terraform-schema to latest revs
  go.mod
  go.sum
Labels: dependencies

#1233 lsp: Recognise new token type for function name
  docs/syntax-highlighting.md
  internal/langserver/handlers/semantic_tokens_test.go
  internal/lsp/token_encoder.go
Labels: enhancement

#1256 deps: Pull in gopls v0.10.0 tsprotocol.go
  internal/langserver/handlers/complete_test.go
  internal/langserver/handlers/completion_resolve_test.go
  internal/langserver/handlers/go_to_ref_target.go
  internal/langserver/handlers/handlers_test.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/langserver/handlers/workspace_symbol_test.go
  internal/lsp/document_links.go
  internal/lsp/location_links.go
  internal/protocol/gen.go
  internal/protocol/gen/gen.go
  internal/protocol/protocol.go
  internal/protocol/protocol_document_changes.go
Labels: bug, dependencies

#1258 Cache registry module errors
  internal/registry/module.go
  internal/state/module.go
  internal/state/registry_modules.go
  internal/state/registry_modules_test.go
  internal/state/state.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
Labels: enhancement

#1266 ci: Remove automated milestone closure commenting
  .github/workflows/milestone-closed.yml
Labels: ci
