Repository hashicorp/terraform-ls, pull requests merged in 2023-02, with the labels that each got.

#1154 ci: Release binaries via CRT
  .github/CODEOWNERS
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test.yml
  .gitignore
  .goreleaser.yml
  .release/ci.hcl
  .release/security-scan.hcl
  version.go
  version/VERSION
Labels: ci

#1166 ci: Remove old release workflow
  .github/workflows/release.yml
Labels: ci

#1168 CONTRIBUTING.md: Add release guide
  .github/CONTRIBUTING.md
Labels: documentation

#1172 Continue parsing module files on error
  internal/terraform/parser/module.go
  internal/terraform/parser/module_test.go
  internal/terraform/parser/testdata/invalid-links/invalid.tf
  internal/terraform/parser/testdata/invalid-links/resources.tf
Labels: bug

#1174 Bump hcl-lang to `bb2205` & terraform-schema to `43c2de`
  go.mod
  go.sum
Labels: dependencies

#1180 deps: bump terraform-schema to `62b1929`
  go.mod
  go.sum
Labels: enhancement

#1193 Disable cgo for builds
  .github/workflows/build.yml
Labels: ci
