Repository hashicorp/terraform-ls, pull requests merged in 2023-10, with the labels that each got.

#1426 Update early validation setting to `enabled` by default
  go.mod
  go.sum
  internal/indexer/document_change.go
  internal/indexer/document_open.go
  internal/langserver/handlers/initialize.go
  internal/settings/settings.go
Labels: enhancement

#1434 settings: Fix option name to `enableEarlyValidation`
  internal/settings/settings.go
Labels: bug

#1435 fix: continue running jobs even if loading metadata fails
  internal/indexer/document_change.go
Labels: bug

#1436 fix option name (early -> enhanced)
  internal/settings/settings.go
Labels: bug

#1433 docs: Document enhanced validation feature
  docs/SETTINGS.md
  docs/images/validation-rule-deprecated-attribute.png
  docs/images/validation-rule-deprecated-block.png
  docs/images/validation-rule-exceeded-block-max-items.png
  docs/images/validation-rule-hcl.png
  docs/images/validation-rule-invalid-ref.png
  docs/images/validation-rule-label-count.png
  docs/images/validation-rule-missing-attribute.png
  docs/images/validation-rule-missing-blocks.png
  docs/images/validation-rule-tfvars-unexpected-blocks.png
  docs/images/validation-rule-tfvars-unknown-var.png
  docs/images/validation-rule-unexpected-attribute.png
  docs/images/validation-rule-unexpected-block.png
  docs/validation.md
Labels: documentation, diagnostics

#1422 Update ParseVariables for single files
  internal/terraform/ast/variables.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/testdata/single-file-change-module/example.tfvars
  internal/terraform/module/testdata/single-file-change-module/nochange.tfvars
  internal/terraform/parser/variables.go
Labels: enhancement, performance

#1440 docs/validation: Fix wrong image placement
  docs/images/validation-rule-unexpected-attribute.png
  docs/images/validation-rule-unexpected-block.png
Labels: documentation

#1447 fix: Avoid validating *.tfvars outside of modules
  internal/decoder/decoder.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/testdata/standalone-tfvars/terraform.tfvars
Labels: bug

#1453 Resolve version correctly for backend schema
  go.mod
  go.sum
  internal/decoder/module_schema.go
Labels: bug

#1458 deps: bump hcl-lang to 6ec57d47fbbb
  go.mod
  go.sum
Labels: bug, dependencies, diagnostics

#1459 deps: Bump terraform-schema to 2e7ddf929411
  go.mod
  go.sum
Labels: enhancement, dependencies

#1461 deps: bump terraform-schema to 3c628dc54764
  go.mod
  go.sum
Labels: bug, dependencies

#1456 fix: Work around 'unreliable' input data for Registry modules
  internal/registry/module.go
  internal/registry/module_test.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_mock_responses.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/testdata/unreliable-inputs-module/main.tf
Labels: bug, diagnostics

#1472 validations: Add link in comment to open issue
  internal/decoder/validations/unreferenced_origin.go
Labels: documentation
