Repository hashicorp/terraform-ls, pull requests merged in 2023-12, with the labels that each got.

#1517 Bump terraform-schema & hcl-lang
  go.mod
  go.sum
Labels: dependencies

#1521 go: bump version to 1.21.5
  .go-version
  go.mod
Labels: dependencies

#1167 ci: Automate releasing via bob
  .github/CONTRIBUTING.md
  .github/workflows/release.yml
Labels: ci

#1529 Rename TokenTypeCapsule to TokenTypeComplex
  docs/syntax-highlighting.md
  go.mod
  go.sum
  internal/lsp/token_encoder.go
Labels: technical-debt
