Repository hashicorp/terraform-ls, pull requests merged in 2023-09, with the labels that each got.

#1372 langserver: Avoid re-processing open files after file saving
  internal/langserver/handlers/did_change_watched_files.go
Labels: enhancement, performance

#1374 Bump terraform-schema and hcl-lang
  go.mod
  go.sum
Labels: dependencies

#1378 deps: bump terraform-schema to `90a397096838`
  go.mod
  go.sum
Labels: dependencies

#1379 validations: Limit ref. validation to only LocalOrigin(s)
  internal/decoder/validations/unreferenced_origin.go
  internal/decoder/validations/unreferenced_origin_test.go
Labels: diagnostics

#1384 go.mod: Fix go directive to include patch version
  go.mod
Labels: dependencies

#1395 indexer: Ensure declared module calls get decoded
  go.mod
  go.sum
  internal/indexer/document_change.go
  internal/indexer/module_calls.go
Labels: bug, technical-debt

#1397 Run CI on PRs that don't target `main`
  .github/workflows/build-pr.yml
  .github/workflows/test.yml
Labels: ci

#1402 Introduce `RPCContext` to aid more fine-grained & efficient processing
  internal/context/context.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/scheduler/scheduler_test.go
  internal/state/jobs.go
  internal/state/jobs_test.go
  internal/state/module_changes_test.go
  internal/walker/walker_test.go
Labels: enhancement

#1407 fix: add missing RPCContext to long (nightly) test
  internal/scheduler/scheduler_long_test.go
Labels: bug

#1408 go: bump version to 1.21.1
  .go-version
  go.mod
Labels: ci

#1414 deps: bump hcl-lang to `aa9b38d`
  go.mod
  go.sum
Labels: dependencies

#1404 Update ParseModuleConfiguration to only parse changed file
  internal/context/context.go
  internal/decoder/decoder_test.go
  internal/terraform/ast/module.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/testdata/single-file-change-module/bar.tf
  internal/terraform/module/testdata/single-file-change-module/example.tfvars
  internal/terraform/module/testdata/single-file-change-module/foo.tf
  internal/terraform/module/testdata/single-file-change-module/main.tf
  internal/terraform/parser/module.go
Labels: enhancement, performance

#1413 Introduce validation of `*.tfvars` files
  internal/decoder/decoder.go
  internal/decoder/validators.go
  internal/indexer/document_change.go
  internal/indexer/document_open.go
  internal/state/module.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
  internal/terraform/module/testdata/invalid-tfvars/foo.auto.tfvars
  internal/terraform/module/testdata/invalid-tfvars/terraform.tfvars
  internal/terraform/module/testdata/invalid-tfvars/variables.tf
Labels: enhancement, diagnostics

#1368 Early validation
  internal/context/context.go
  internal/decoder/decoder.go
  internal/decoder/validations/unreferenced_origin.go
  internal/decoder/validations/unreferenced_origin_test.go
  internal/decoder/validators.go
  internal/indexer/document_change.go
  internal/indexer/document_open.go
  internal/langserver/diagnostics/diagnostics.go
  internal/langserver/diagnostics/diagnostics_test.go
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/hooks_module.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/settings/settings.go
  internal/state/module.go
  internal/state/module_test.go
  internal/terraform/ast/diagnostics.go
  internal/terraform/ast/module.go
  internal/terraform/ast/variables.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
  internal/terraform/module/testdata/invalid-config/main.tf
  internal/terraform/module/testdata/invalid-config/variables.tf
  internal/terraform/module/testdata/invalid-tfvars/foo.auto.tfvars
  internal/terraform/module/testdata/invalid-tfvars/terraform.tfvars
  internal/terraform/module/testdata/invalid-tfvars/variables.tf
Labels: enhancement

#1424 Add comments explaining each job's purpose
  internal/terraform/module/module_ops.go
Labels: documentation

#1425 deps: Bump terraform-schema to `7b256e6c65f9`
  go.mod
  go.sum
  internal/langserver/handlers/complete_test.go
Labels: enhancement, dependencies

#1427 context: Replace `RPCContextData` with `DocumentContext`
  internal/context/context.go
  internal/decoder/decoder_test.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/scheduler/scheduler_test.go
  internal/state/jobs.go
  internal/state/jobs_test.go
  internal/state/module_changes_test.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/walker/walker_test.go
Labels: bug, performance
