Repository hashicorp/terraform-ls, pull requests merged in 2023-08, with the labels that each got.

#1332 jobs: Don't wait for `GetModuleDataFromRegistry` job
  internal/indexer/document_change.go
Labels: performance

#1343 deps: Bump terraform-schema to 8234469
  go.mod
  go.sum
Labels: dependencies

#1334 OTEL: Instrument `PreloadEmbeddedSchema` job
  internal/terraform/module/module_ops.go
Labels: enhancement, performance

#1350 deps: Bump terraform-schema to 571f93a5dc94
  go.mod
  go.sum
Labels: dependencies

#1355 go: Bump version to 1.21
  .go-version
  go.mod
  go.sum
Labels: dependencies

#1346 Introduce a new job for running early validation
  go.mod
  go.sum
  internal/decoder/decoder.go
  internal/decoder/validations/unreferenced_origin.go
  internal/decoder/validations/unreferenced_origin_test.go
  internal/indexer/document_change.go
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/hooks_module.go
  internal/state/module.go
  internal/state/module_changes.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
Labels: enhancement

#1361 Centralize diagnostics publishing
  go.mod
  go.sum
  internal/decoder/decoder.go
  internal/decoder/validations/unreferenced_origin.go
  internal/decoder/validations/unreferenced_origin_test.go
  internal/indexer/document_change.go
  internal/langserver/diagnostics/diagnostics.go
  internal/langserver/diagnostics/diagnostics_test.go
  internal/langserver/handlers/command/validate.go
  internal/langserver/handlers/hooks_module.go
  internal/state/module.go
  internal/state/module_changes.go
  internal/state/module_test.go
  internal/terraform/ast/diagnostics.go
  internal/terraform/ast/module.go
  internal/terraform/ast/variables.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/operation/op_type_string.go
  internal/terraform/module/operation/operation.go
Labels: enhancement

#1369 Improve `PreloadEmbeddedSchema` performance
  internal/state/provider_schema.go
  internal/terraform/module/module_ops.go
Labels: bug, performance

#1370 Only validate a single file on `didChange`
  go.mod
  go.sum
  internal/context/context.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/state/jobs.go
  internal/terraform/module/module_ops.go
  internal/terraform/module/module_ops_test.go
  internal/terraform/module/testdata/invalid-config/main.tf
  internal/terraform/module/testdata/invalid-config/variables.tf
Labels: enhancement, performance
