Repository hashicorp/terraform-ls, pull requests merged in 2023-07, with the labels that each got.

#1295 Change nvim_create_autocmd callback to a lambda
  docs/USAGE.md
Labels: documentation, waiting-response

#1327 OTEL instrumentation
  go.mod
  go.sum
  internal/cmd/inspect_module_command.go
  internal/cmd/serve_command.go
  internal/indexer/document_change.go
  internal/indexer/document_open.go
  internal/indexer/module_calls.go
  internal/indexer/walker.go
  internal/indexer/watcher.go
  internal/job/job_id.go
  internal/job/job_store.go
  internal/langserver/handlers/did_change.go
  internal/langserver/handlers/did_change_watched_files.go
  internal/langserver/handlers/did_change_workspace_folders.go
  internal/langserver/handlers/did_open.go
  internal/langserver/handlers/initialize.go
  internal/langserver/handlers/service.go
  internal/langserver/langserver.go
  internal/registry/module.go
  internal/registry/registry.go
  internal/scheduler/scheduler.go
  internal/scheduler/scheduler_test.go
  internal/state/jobs.go
  internal/state/jobs_test.go
  internal/state/module_changes_test.go
  internal/state/state.go
  internal/state/walker_paths.go
  internal/state/walker_paths_test.go
  internal/terraform/exec/exec.go
  internal/walker/walker.go
  internal/walker/walker_test.go
Labels: enhancement, performance

#1335 fix: Add missing context argument to a test
  internal/scheduler/scheduler_long_test.go
Labels: bug
