Repository hashicorp/terraform-ls, pull requests merged in 2024-01, with the labels that each got.

#1548 Rename `CandidatesAtPos` to `CompletionAtPos`
  go.mod
  go.sum
  internal/langserver/handlers/complete.go
  internal/langserver/handlers/complete_test.go
Labels: technical-debt

#1572 github: Revert upgrade of artifact actions
  .github/workflows/benchmarks.yml
  .github/workflows/build.yml
Labels: dependencies

#1574 Rename `*Traversal*` to `*Reference*`
  docs/syntax-highlighting.md
  go.mod
  go.sum
  internal/lsp/completion.go
  internal/lsp/symbols.go
  internal/lsp/token_encoder.go
Labels: technical-debt

#1580 github: Grant `actions: write` permission
  .github/workflows/build.yml
Labels: ci

#1582 github: Pass token explicitly to delete-artifact
  .github/workflows/build.yml
Labels: ci

#1583 Bump terraform-schema and hcl-lang
  go.mod
  go.sum
Labels: dependencies

#1595 Bump terraform-schema & hcl-lang
  go.mod
  go.sum
Labels: dependencies

#1599 github: Remove benchmarks workflow
  .github/workflows/benchmarks.yml
Labels: ci
